### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by ZedZipDev** [nberglund/RabbitMQ-SqlServer#2]
I have created SQLCLR, all is ok.
Then try this
EXEC dbo.pr_SomeProcessingStuff @id = 101
But receive
```
Msg 50000, Level 16, State 1, Procedure dbo.pr_SomeProcessingStuff, Line 29 [Batch Start Line 20]
Error: Error: A .NET Framework error occurred during execution of user-defined routine or aggregate "pr_clr_PostRabbitMsg": 
System.ApplicationException: Channel pool blocked when trying to post message to Exchange: amq.direct.
System.ApplicationException: 
   at RabbitMQSqlClr.RabbitPublisher.Post(String exchange, Byte[] msg, String topic)
   at RabbitMQSqlClr.RabbitMQSqlServer.pr_clr_PostRabbitMsg(Int32 endPointId, String msgToPost)
. at line: 0 at line: 13

```
I have changed the amq.direct -> amq.topic but the same error.
I use SQL Server 2019 and RabbitMQ Docker
`docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management`

Where am I wrong? what to fix?

**Comment by Unknown008** [comment]
I was having the same issue. I ended up using the solution posted on this stackoverflow answer: https://stackoverflow.com/a/54699813

- I first installed Python 2.7.9
- I then downloaded RabbitMQAdmin (was available on http://localhost:15672/cli/rabbitmqadmin. The documentation is here: https://www.rabbitmq.com/docs/management-cli)
- I added the python path to my environment variable PATHs
  
   ![image](https://github.com/user-attachments/assets/21c349d4-32ff-4625-aa01-fdcce3b3526b)

- Ran the SQL script:

    ```
    DECLARE @Cmd VARCHAR(2000)
    SET @Cmd = 'C:/Python27/python.exe C:/rabbitmq/rabbitmqadmin publish exchange=amq.default routing_key=locationSampleQueue payload="test"'
    EXEC [sys].[xp_cmdshell] @Cmd
    ```
`locationSampleQueue` is a queue name I was testing. Substitute with the queue name you are using. I also copied the rabbitmqadmin file to the `C:/rabbitmq` directory that I created.
